device: 'cuda'
gpu_index: "0"

federation_id: 'lenet_mnist'
federated_learning_schema: 'TraditionalFederatedLearning'
client_role: 'train'

learning_rate: 0.001
model_type: "LENET"
pretrained_models: false
dataset_type: "mnist"

data_distribution_kind: "20"
desired_distribution: null
dirichlet_beta: 0.5

distance_metric: "coordinate"
dynamic_sensitivity_percentage: true
sensitivity_percentage: 100
remove_common_ids: false
fed_avg: false

aggregation_strategy: "FedAvg"
aggregation_sample_scaling: false

distance_metric_on_parameters: true
number_of_epochs: 2
train_batch_size: 64
test_batch_size: 128
transform_input_size: 28
weight_decay: 1e-4

number_of_clients: 10
client_sampling_rate: 1.0
pre_computed_data_driven_clustering: false
do_cluster: true
clustering_period: 5
federated_learning_rounds: 30
stop_avg_accuracy: 0.95
save_before_aggregation_models: false
save_global_models: false

# Encryption
encryption_method: "he_xmkckks"
xmkckks_weight_decimals: 8 