device: 'cuda'
gpu_index: "0"

federation_id: '1.x.y'
# TraditionalFederatedLearning | ClusterFederatedLearningSchema
federated_learning_schema: 'TraditionalFederatedLearning'
# train | test | eval | train-test-eval | train-eval | etc.
client_role: 'train'

learning_rate: 0.001
model_type: "cnn"
pretrained_models: false
dataset_type: "fmnist"

data_distribution_kind: "20"
desired_distribution: null
dirichlet_beta: 0.5

distance_metric: "coordinate"
dynamic_sensitivity_percentage: true
sensitivity_percentage: 100
remove_common_ids: false
fed_avg: false

# FedAvg | FedProx
aggregation_strategy: "FedAvg"
aggregation_sample_scaling: false

distance_metric_on_parameters: true
number_of_epochs: 1
train_batch_size: 128
test_batch_size: 256
transform_input_size: 28
weight_decay: null

number_of_clients: 10
client_sampling_rate: 1.0
pre_computed_data_driven_clustering: false
do_cluster: true
clustering_period: 6
federated_learning_rounds: 10
stop_avg_accuracy: 1.0
save_before_aggregation_models: false
save_global_models: false

